
# jr@oblique:  1/10/14


FactoryGirl.define do

  factory :map do
    name         "This is a map"
    #name     	  "Restaurants"
    #name        "Meditation"
    #map_type 		"Test"
    #created_by 	"Javier"
    #last_updated_by 	"Javier"
    #comments 	  "Generated by Factory Girl"
  end

  factory :point do
    name "Photonika"
    map
  end

end



#FactoryGirl.define do
#  factory :restaurant do
#    name       "Raw cafe"
#    info   "crudivegan"
#    lat_dec    "11"
#    long_dec "21"
#  end
#end
FactoryGirl.define do
  factory :restaurant do
    sequence(:name)  		   { |n| "Resto #{n}" }
    sequence(:info)  		   { |n| "Info_#{n}"}
    sequence(:lat_dec)  	 { |n| "Lat_#{n}"}
    sequence(:lng_dec)  	 { |n| "Long_#{n}"}

    sequence(:point_type)       { "restaurant"}

    sequence(:created_by)       { "Javier"}
    sequence(:last_updated_by)  { "Javier"}
    sequence(:ad_number)        {"1"}
    sequence(:ad_street)        {"av. Arequipa"}
    #factory :admin do
    #  admin true
    #end
    
  end
end